Update post schema and added feed
jrwyman/TinyPage pull request #1
Opened 2020-12-03 19:42 UTC by jrwyman

- update post schema
- added feed to replace "posts" page

2020-12-03 19:43 UTC, wymtime commented on backend/routes/posts.js
> +    Post.find({ user: { id: req.params.user_id } })   /* THE ISSUE WITH PROFILE CARD NOT SHOWING POSTS IS HERE */
This looks good

2020-12-04 04:22 UTC, wymtime requested changes

2020-12-04 04:22 UTC, wymtime commented on frontend/src/components/feed/feed.css
> +    word-wrap: break-word;
This is an outdated css rule. Use `overflow-wrap` instead

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

2020-12-04 04:22 UTC, wymtime commented on frontend/src/components/feed/feed.jsx
> +    componentWillMount() {
Don't fetch data with `componentWillMount`, use `componentDidMount` instead.

https://www.robinwieruch.de/react-fetching-data#where-to-fetch-in-reacts-component-tree

2020-12-04 04:22 UTC, wymtime commented on frontend/src/components/feed/feed.jsx
> +        this.setState({ posts: newState.posts });
Instead of setting the posts in react `state`, use your redux state instead. There's no need to have two copies of the same data, one in redux and another in react state.

2020-12-04 04:22 UTC, wymtime commented on frontend/src/components/feed/feed.jsx
> +        if (this.state.posts.length === 0) {
After updating according to the comment above, use this.props.posts instead.

Ex.

`const { posts } = this.props;`

2020-12-04 04:22 UTC, wymtime commented on frontend/src/components/feed/feed.jsx
> +    componentWillReceiveProps(newState) {
For clarity, this shouldn't be called `newState`, it should be called `nextProps`. This lifecycle method is also deprecated. If you do need to _derive_ (copy) values from props for state, use componentDidUpdate instead.

https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

2020-12-04 04:22 UTC, wymtime commented on frontend/src/components/nav/navbar.jsx
> +            <img className="logo" src={logo} alt="logo" width="100px" />
I don't think you need to hardcode this width value into this img element. Instead create a class and set the width there. Or create a div around the img element and add the class to that.

2020-12-04 04:22 UTC, wymtime commented on frontend/src/components/posts/post_compose.jsx
> +    componentWillReceiveProps(nextProps) {  //deprecated
Use the `newPost` prop instead of deriving this value into react `state`.

Will you allow post editing as well? If you do, then you may want to actually copy the `newPost` prop into state. You can then edit the newPost text in state and then update it again. If that's the case, use `componentDidUpdate` instead of `componentWillReceiveProps`

2020-12-04 04:22 UTC, wymtime commented on frontend/src/components/posts/post_compose.jsx
> +                            value={this.state.text}
Instead of `this.state.text`, do `const { text } = this.state;`

Cleaner/easier to read.

2020-12-04 04:22 UTC, wymtime commented on frontend/src/components/profile/profile.jsx
> +                        {this.state.posts.map(post => (
Change to `const { posts } = this.state`

2020-12-04 04:22 UTC, wymtime commented on frontend/src/components/session/login_form.jsx
> +                    {Object.keys(this.props.errors).map((error) => (
Change to `const { errors } = this.props;`

2020-12-04 04:22 UTC, wymtime commented on frontend/src/components/session/signup_form.jsx
> +        if (this.props.errors) {
`const { errors } = this.props`

2020-12-04 04:22 UTC, wymtime commented on frontend/src/reducers/posts_reducer.js
> +    new: undefined,
What does `new` mean in this example? If its a post, rename this variable/key to something more descriptive.

Ex. `newPost`

2020-12-04 21:17 UTC, jrwyman commented on frontend/src/components/feed/feed.css
> +    word-wrap: break-word;
fixed.

2020-12-04 21:17 UTC, jrwyman commented on frontend/src/components/feed/feed.jsx
> +    componentWillMount() {
fixed.

2020-12-04 21:18 UTC, jrwyman commented on frontend/src/components/feed/feed.jsx
> +        this.setState({ posts: newState.posts });
Removed posts from react state and used componentDidUpdate instead. fixed.

2020-12-04 21:20 UTC, jrwyman commented on frontend/src/components/feed/feed.jsx
> +        if (this.state.posts.length === 0) {
fixed.

2020-12-09 23:15 UTC, merged